### PR TITLE
graylog-server shoudn't add elasticsearch node.

### PR DESCRIPTION
**Pull request by mariusgrigaitis**
This is done by elasticsearch recipe.

### CODE REVIEW

**Comment by mariusgrigaitis** [comment]
Can we automate this somehow then and move it to elasticsearch script?

Currently if you're not running elasticsearch on the same machine it, it adds ip addresses into etcd which doesn't actually point to elasticsearch?

I'm thinking about something like when etcd contents changes (added elasticsearch) -> reconfigure

**Comment by mariussturm** [comment]
The thing is, Graylog itself works as an Elasticsearch node. The server connects to a ES cluster as a node that stores no data and will never be the master. So if you want to spin up a new GL server you have to add it as an additional ES node.

But the elasticsearch.rb recipe is only executed when you add another _data_ node, so you end up with a broken cluster configuration otherwise.

Currently there is no long running process on the appliances that could monitor a change in Etcd to trigger a reconfigure automatically of the whole cluster. What is the underlying problem to this?

**Comment by mariusgrigaitis** [comment]
I want to configure cluster by spinning up graylog-server + etcd + mongodb as master, then spin up another one with elasticsearch and make them work together.

Basically what i'm trying to achieve is http://docs.graylog.org/en/latest/pages/architecture.html#bigger-production-setup

**Comment by mariussturm** [comment]
Except the MongoDB replica set you can do this with the omnibus package/official images:

``` shell
vm1> sudo graylog-ctl reconfigure
```

``` shell
vm2> sudo graylog-ctl set-cluster-master <ip-of-vm1>
vm2> sudo graylog-ctl reconfigure-as-backend
```

You end up with two graylog-server instances and on each a running elasticsearch for data storage. Mongodb and web interface are running on vm1 then.

**Pull request closed without merging**
