### PR TITLE
Support retrieval of SSL certificate/key pair

### PR DESCRIPTION
**Pull request by brandongalbraith**
Use built-in Graylog SSL functionality to support native SSL. 

Provide URLs to both GRAYLOG_SSL_CERTIFICATE_URL and GRAYLOG_SSL_PRIVATEKEY_URL environment variables to have certificate and key retrieved by curl, placed on filesystem, and nginx restarted once done.

### CODE REVIEW

**Comment by mariussturm** [comment]
The curl in the start script looks odd to me. Not sure about another solution at the moment, but this is a little bit fragile. People can easily break the startup process by providing a wrong url. Another point is that the private key needs to be freely accessable in the network. Not a good pratice.
Maybe there is something in Docker we can use to provide a file to the container?

**Comment by brandongalbraith** [comment]
@mariussturm I should've provided more context, my apologies. Fetching a private key in this manner is safe when the URL is authenticated through the URL query string (for example, a short-lived signed request over HTTPS to an AWS S3 bucket containing the cert and the key).

Would you be more comfortable with this functionality if I fetched the key and cert, verified they were proper cert/key files using openssl, and then performing a move operation into place? The only other way to do this would be to use a Docker ADD command to add the keys from the local filesystem, which means you must rely on an external process to retrieve the necessary SSL cert/key files.

I'm fine if this doesn't get merged, as I understand it might be considered more environment specific. Feel free to close the PR without merging if that's the case.

**Comment by mariussturm** [comment]
To keep the start script clean I would try to expose the `/opt/graylog/conf/nginx/ca` folder. So people can deploy certificates to the Docker host and make use of it inside of the container. This needs some logic to the Chef recipes to make use of the certificates. Could you open an issue for this? I will experiment a little bit in the next days.

**Comment by brandongalbraith** [comment]
:+1:

**Pull request closed without merging**
